version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle-genius
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


#  vehicle_genius_api:
#    build: ./VehicleGenius.Api
#    ports:
#      - "5000:5000"
#    depends_on:
#      - postgres

volumes:
  postgres:
  rabbitmq:
